[package]
name = "rusty_locounter"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_derive = "1.0.203"
serde = { version = "1.0.117", features = ["derive"] }
tinyfiledialogs = "3.9.1"
directories = "5.0.1"
lazy_static = "1.4.0"
iced = "0.13.1"
