[package]
name = "rusty_locounter"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.27.2"
egui = "0.27.2"
serde_derive = "1.0.203"
serde = { version = "1.0.117", features = ["derive"] }
tinyfiledialogs = "3.9.1"
directories = "5.0.1"
